CREATE TABLE overwatch_db (
primary_key INT PRIMARY KEY,
start_time DATE,
match_id FLOAT,
map_name TEXT,
player TEXT,
team TEXT,
hero TEXT,
all_damage_done FLOAT,
assists FLOAT,
average_time_alive FLOAT,
barrier_damage_done FLOAT,
damage_quick_melee FLOAT,
damage_blocked FLOAT,
damage_done FLOAT,
damage_taken FLOAT,
deaths FLOAT,
defensive_assists FLOAT,
eliminations FLOAT,
environmental_deaths FLOAT,
environmental_kills FLOAT,
final_blows FLOAT,
healing_done FLOAT,
hero_damage_done FLOAT,
melee_final_blows FLOAT,
melee_percentage_of_final_blows FLOAT,
multikills FLOAT,
objective_kills FLOAT,
objective_time FLOAT,
offensive_assists FLOAT,
recon_assists FLOAT,
shots_fired FLOAT,
solo_kills FLOAT,
teleporter_pads_destroyed FLOAT,
time_alive FLOAT,
time_building_ultimate FLOAT,
time_elapsed_per_ultimate_earned FLOAT,
time_holding_ultimate FLOAT,
time_played FLOAT,
turrets_destroyed FLOAT,
ultimates_earned_fractional FLOAT,
ultimates_used FLOAT,
weapon_accuracy FLOAT
);

Select * from overwatch_db
