CREATE TABLE overwatch_18_19 (
index TEXT PRIMARY KEY,
start_time FLOAT,
match_id FLOAT,
map_name TEXT,
player TEXT,
team TEXT,
hero TEXT,
"All_Damage_Done" FLOAT,
"Assists" FLOAT,
"Average_Time_Alive" FLOAT,
"Barrier_Damage_Done" FLOAT,
"Damage_Quick_Melee" FLOAT,
"Damage_Blocked" FLOAT,
"Damage_Done" FLOAT,
"Damage_Taken" FLOAT,
"Deaths" FLOAT,
"Defensive_Assists" FLOAT,
"Eliminations" FLOAT,
"Environmental_Deaths" FLOAT,
"Environmental_Kills" FLOAT,
"Final_Blows" FLOAT,
"Healing_Done" FLOAT,
"Hero_Damage_Done" FLOAT,
"Melee_Final_Blows" FLOAT,
"Melee_Percentage_of_Final_Blows" FLOAT,
"Multikills" FLOAT,
"Objective_Kills" FLOAT,
"Objective_Time" FLOAT,
"Offensive_Assists" FLOAT,
"Recon_Assists" FLOAT,
"Shots_Fired" FLOAT,
"Solo_Kills" FLOAT,
"Teleporter_Pads_Destroyed" FLOAT,
"Time_Alive" FLOAT,
"Time_Building_Ultimate" FLOAT,
"Time_Elapsed_per_Ultimate_Earned" FLOAT,
"Time_Holding_Ultimate" FLOAT,
"Time_Played" FLOAT,
"Turrets_Destroyed" FLOAT,
"Ultimates_Earned_Fractional" FLOAT,
"Ultimates_Used" FLOAT,
"Weapon_Accuracy" FLOAT
);

Select * from overwatch_18_19
